import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarTwo from "@/components/NavbarTwo";
import { Playfair_Display } from "next/font/google";
import Footer from "../components/Footer";

const playfair_display = Playfair_Display({
  variable: "--font-text",
  subsets: ["latin"],
  weight: ["400", "900"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Mercedes Benz",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${playfair_display.variable} ${geistMono.variable} font-text scroll-smooth antialiased`}
      >
        <NavbarTwo />
        <div className="mt-[72px] ">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
